import {
  FileCheck,
  FileText,
  Receipt,
  Shield,
  Zap,
  Star,
  Award,
  CheckCircle,
  Info,
  AlertCircle,
  Truck,
  CreditCard,
  Lock,
  PieChart,
  BarChart3,
  Mail,
  MessageCircle,
  Calendar,
  Users,
  Building2,
  Sparkles,
  BadgeCheck,
  Wallet,
  FileSpreadsheet,
  type LucideIcon,
} from 'lucide-react'

/** Liste des icônes disponibles pour les messages dashboard (admin). */
export const DASHBOARD_MESSAGE_ICONS = [
  { value: 'FileCheck', label: 'Coche document' },
  { value: 'FileText', label: 'Document texte' },
  { value: 'Receipt', label: 'Reçu' },
  { value: 'Shield', label: 'Bouclier' },
  { value: 'Zap', label: 'Éclair' },
  { value: 'Star', label: 'Étoile' },
  { value: 'Award', label: 'Récompense' },
  { value: 'CheckCircle', label: 'Cercle validé' },
  { value: 'Info', label: 'Info' },
  { value: 'AlertCircle', label: 'Alerte' },
  { value: 'Truck', label: 'Camion' },
  { value: 'CreditCard', label: 'Carte bancaire' },
  { value: 'Lock', label: 'Cadenas' },
  { value: 'PieChart', label: 'Graphique camembert' },
  { value: 'BarChart3', label: 'Graphique barres' },
  { value: 'Mail', label: 'Mail' },
  { value: 'MessageCircle', label: 'Message' },
  { value: 'Calendar', label: 'Calendrier' },
  { value: 'Users', label: 'Utilisateurs' },
  { value: 'Building2', label: 'Bâtiment' },
  { value: 'Sparkles', label: 'Étincelles' },
  { value: 'BadgeCheck', label: 'Badge validé' },
  { value: 'Wallet', label: 'Portefeuille' },
  { value: 'FileSpreadsheet', label: 'Tableur' },
] as const

export type DashboardMessageIconName = (typeof DASHBOARD_MESSAGE_ICONS)[number]['value']

const iconMap: Record<string, LucideIcon> = {
  FileCheck,
  FileText,
  Receipt,
  Shield,
  Zap,
  Star,
  Award,
  CheckCircle,
  Info,
  AlertCircle,
  Truck,
  CreditCard,
  Lock,
  PieChart,
  BarChart3,
  Mail,
  MessageCircle,
  Calendar,
  Users,
  Building2,
  Sparkles,
  BadgeCheck,
  Wallet,
  FileSpreadsheet,
}

export function getDashboardMessageIcon(name: string): LucideIcon {
  return iconMap[name] ?? Info
}
